"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=$%2gz&6zw9g0fgr8uoped06m#x+^h^322x@aiwhdwtg!evv0s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# Aqui se listan las aplicaciones en activo del proyecto
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "rest_framework",   # App para creación de APIs facilmente
    "api",              # Indicando mi propia api
    "drf_spectacular",  # Swagger, usando OpenApi para generar documentación
    'import_export',    # Para poder importar y exportar CSV
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# URL base donde sedarán los archivos estaticos
STATIC_URL = 'static/'

# Ruta raiz del proyecto
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = "/media/"           # URL para acceder a archivos multimedia
MEDIA_ROOT = BASE_DIR / "media" # Nombre de la carpeta donde estan los archivos

REST_FRAMEWORK = {
    # La sigiente linea indica la clase con la que se genera la documentación cuando se cambien los endpoints de la API
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",

    # Indicación de clases de autentificación para la API 
    # Se aplica en POST, PUT, PATCH, DELETE
    "DEFAULT_AUTHENTICATION_CLASSES":(
        # Atutentificación basada en JWT
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    # Clase que indica quien puede modificar los datos
    "DEFAULT_PERMISSION_CLASSES":(
        # Actualmente pueden modificar todo el mundo
        #'rest_framework.permissions.AllowAny',
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    )
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Tennis API",
    "DESCRIPTION": "API para gestión de jugadores y partidos de tenis",
    "VERSION": "1.0.0",
}

ALLOWED_HOSTS = ["*"]