# Generated by Django 6.0 on 2025-12-26 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('pais', models.CharField(max_length=50)),
                ('bandera', models.CharField(blank=True, max_length=5, null=True)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('ranking_atp', models.IntegerField(blank=True, null=True)),
                ('mejor_ranking', models.IntegerField(blank=True, null=True)),
                ('mano_dominante', models.CharField(choices=[('D', 'Diestra'), ('Z', 'Zurda')], max_length=1)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jugadores/')),
                ('estadisticas', models.JSONField(blank=True, default=dict)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
