# Generated by Django 5.2.10 on 2026-01-28 15:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150, unique=True)),
                ('pais', models.CharField(max_length=50)),
                ('bandera', models.CharField(blank=True, max_length=5, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('ranking_atp', models.IntegerField(blank=True, null=True)),
                ('mejor_ranking', models.IntegerField(blank=True, null=True)),
                ('mano_dominante', models.CharField(choices=[('D', 'Diestra'), ('Z', 'Zurda')], max_length=1)),
                ('foto', models.ImageField(blank=True, default='jugadores/default.png', null=True, upload_to='jugadores/')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pen', 'Pendiente'), ('gam', 'En Juego'), ('fin', 'Finalizado')], default='pen', max_length=3)),
                ('competicion', models.CharField(max_length=200)),
                ('fase', models.CharField(choices=[('1', 'Final'), ('2', 'Semi-final'), ('3', 'Cuartos de final'), ('4', 'Octavos de final'), ('5', 'Dieciseisavos de final'), ('6', '2ª Ronda'), ('7', '1ª Ronda'), ('8', 'Fase Previa'), ('0', 'Amistoso')], default='0', max_length=1)),
                ('annio', models.PositiveIntegerField()),
                ('fecha_iniciado', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizado', models.DateTimeField(blank=True, null=True)),
                ('is_tie_break', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('arbitro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_arbitrados', to=settings.AUTH_USER_MODEL)),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_ganados', to='api.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='PartidoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_jugador1', models.BooleanField(default=True)),
                ('sets_1', models.PositiveIntegerField(default=0)),
                ('sets_2', models.PositiveIntegerField(default=0)),
                ('sets_3', models.PositiveIntegerField(default=0)),
                ('saque', models.BooleanField(default=False)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='api.partido')),
            ],
        ),
    ]
