# Generated by Django 6.0 on 2025-12-26 21:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competicion', models.CharField(max_length=200)),
                ('fase', models.CharField(max_length=50)),
                ('annio', models.PositiveIntegerField()),
                ('fecha_finalizado', models.DateTimeField(blank=True, null=True)),
                ('is_tie_break', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_ganados', to='api.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='PartidoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_Jugador1', models.BooleanField()),
                ('sets_1', models.PositiveIntegerField(default=0)),
                ('sets_2', models.PositiveIntegerField(default=0)),
                ('sets_3', models.PositiveIntegerField(default=0)),
                ('saque', models.BooleanField(default=False)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='api.partido')),
            ],
        ),
    ]
