# Generated by Django 5.2.10 on 2026-02-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidoparticipante',
            name='puntos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
