# Generated by Django 6.0 on 2025-12-30 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_partido_partidoparticipante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='estadisticas',
        ),
        migrations.AddField(
            model_name='partido',
            name='arbitro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_arbitrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partido',
            name='estado',
            field=models.CharField(choices=[('pen', 'Pendiente'), ('gam', 'En Juego'), ('fin', 'Finalizado')], default='pen', max_length=3),
        ),
        migrations.AddField(
            model_name='partido',
            name='fecha_iniciado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='fase',
            field=models.CharField(choices=[('1', 'Final'), ('2', 'Semi-final'), ('3', 'Cuartos de final'), ('4', 'Octavos de final'), ('5', 'Dieciseisavos de final'), ('6', '2ª Ronda'), ('7', '1ª Ronda'), ('8', 'Fase Previa'), ('0', 'Amistoso')], default='0', max_length=1),
        ),
    ]
