# Generated by Django 6.0 on 2025-12-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_jugador_estadisticas_partido_arbitro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partidoparticipante',
            name='es_Jugador1',
        ),
        migrations.AddField(
            model_name='partidoparticipante',
            name='es_jugador1',
            field=models.BooleanField(default=True),
        ),
    ]
