# Generated by Django 5.2.10 on 2026-01-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_partidoparticipante_es_jugador1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='foto',
            field=models.ImageField(blank=True, default='jugadores/default.png', null=True, upload_to='jugadores/'),
        ),
        migrations.AlterField(
            model_name='partidoparticipante',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
